version: "3.7"
services:
  backend:
    image: willdobbins/readme_be:latest
    depends_on:
      - redis
    ports:
      - "80:5000"
    environment:
      FLASK_ENV: development
      FLASK_APP: readme_be
    volumes:
      - .:/usr/src/app
  redis:
    image: redis:latest
